"""Migrations and ORM models must describe the same schema (`alembic check`)."""

from __future__ import annotations

from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from alembic import command


def test_models_match_migrations(test_database_url: str, database_available: bool) -> None:
    config = Config("alembic.ini")
    config.set_main_option("sqlalchemy.url", test_database_url.replace("%", "%%"))
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure message only
        raise AssertionError(f"model/migration drift: {exc}") from exc
